project:
  type: website

website:
  title: "Jason Haw"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example-analysis.qmd
        text: Example Analysis

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto
